### ISSUE TITLE
SSE/AVX optimization

### ISSUE THREAD

**Issue by tormento** [kekyo/fdk-aac-win32-builder#1]
Would you please add switches to compile with SSE and/or AVX optimizations?

**Comment by kekyo** [comment]
@tormento I pushed updated scripts now 52cccdf3fe42126f7b22fdeefc998525c47823db

It contains default optimization for platform natives and LTO.
You have to choose option in build.sh if you have to AVX-512 option.

```sh
###################################
# Compiler optimization flags:

# Platform native (not include AVX-512, it's standard options)
CFLAGS="-O3 -flto -march=native"

# AVX-512
#CFLAGS="-O3 -flto -march=native -mavx512f -mavx512dq -mavx512er -mavx512cd -mavx512bw -mavx512pf -mavx512vl -mavx512ifma -mavx512vbmi"

# For debugging/reference usage
#CFLAGS="-O0"

###################################
```

And added new PCM verifier script named `test.sh`
My environment doesn't cause any error with AVX-512 and some AAC encoded formats.

**Comment by tormento** [comment]
@kekyo thanks!

What to set to optimize for standard AVX only?

**Comment by kekyo** [comment]
@tormento It's environment depended, `-march=native` is use options by building CPU environment except AVX-512. If you use AVX enabled CPU, the build.sh script will make AVX enabled binary.

Or we can force set immediately options using `-m` options. (ex: `-mavx`) Insert it into CFLAGS line. See https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html

**Comment by tormento** [comment]
@kekyo I asked to be able to build binaries for other CPUs :)

**Comment by kekyo** [comment]
@tormento For example (in `build.sh` head)

```sh
CFLAGS="-O3 -flto -mavx"
```

Varies of options are many, you can find by web browser search tabs in the gcc man page above.

**Comment by kekyo** [comment]
> What about creating a script for compiling ffmpeg with fdkaac support too?

I don't have ffmpegs builder script now. It's complex rather than fdk...

**Comment by tormento** [comment]
Perhaps you could update readme.md to reflect switches possibilities.
