### ISSUE TITLE
Here it is build.sh to have no dependencies on x86 code

### ISSUE THREAD

**Issue by tormento** [kekyo/fdk-aac-win32-builder#2]
[build.zip](https://github.com/kekyo/fdk-aac-win32-builder/files/4499538/build.zip)
Please notice that this build.sh can create x86 code with NO dependencies.

P.S: -j40 is an overkill. I suggest to use the number of your logical cores.

**Comment by kekyo** [comment]
@tormento Thank you sent it and sorry too later respond. I'll merge it!

**Comment by kekyo** [comment]
I made it! thanks!

![image](https://user-images.githubusercontent.com/6181948/86250926-30957a80-bbec-11ea-9b45-6cf43e2073ec.png)
