### ISSUE TITLE
Potentially better choice of compilation threads

### ISSUE THREAD

**Issue by nkh0472** [kekyo/fdk-aac-win32-builder#6]
1. Check the number of CPUs
`cat /proc/cpuinfo |grep "physical id"|sort|uniq|wc -l`
2. Check the number of cores in each physical CPU
`cat /proc/cpuinfo |grep "cpu cores"|uniq|wc -l`
3. Check the number of threads in each CPU core
`cat /proc/cpuinfo |grep "processor"|wc -l`
4. Then the number of threads supported by CPU is the number of CPUs * the number of cores contained in each CPU * the number of threads contained in each core.
5. The ideal number of threads for compilation may be twice the above value. 

That is, for a 4-core processor, the value is 8 threads in the current script `make -j8`. But for other numbers of cores, the value can be changed to show better performance.

These may be a potentially better choice of compilation threads in `\build.sh`.

**Comment by kekyo** [comment]
Nice suggest, I manually adjusted in earlier version.
I tested these scripts. It's simpler at 3 (I'm seriously thinking about how to calculate cpu cores :)
I will insert it.

**Comment by kekyo** [comment]
Merged.
